### ISSUE TITLE
Slides of today (programming style)

### ISSUE THREAD

**Issue by aunis** [natj/CompCoffee#3]
It seems that I can see the slides of today's CompCoffee only as html code (https://github.com/TuorlaObservatory/CompCoffee/tree/master/programming-styles). Is it just me or is there something missing?

**Comment by Ilia-Kosenkov** [comment]
You can view it in you browser if you download it (`git clone` or `git pull`). I will upload pdf in a few minutes.

**Comment by Ilia-Kosenkov** [comment]
Presentation can be found [here](https://github.com/TuorlaObservatory/CompCoffee/blob/master/programming-styles/slides/Programming%20style.pdf)

The initial presentation is prepared using [**Remark**](https://remarkjs.com/#1). You can give it a shot if you want.
